export const translation = {
    "en": {
      "add_new_member": "Add New Member",
      "watch_previous_data": "Watch previous data",
      "my_clients": "My Clients",
      "edit": "Edit",
      "client_detail": "Client Detail",
      "full_name": "Full Name",
      "cast": "Cast",
      "phone_number": "Phone Number",
      "address": "Address",
      "optional": "Optional",
      "name_required": "Name is required.",
      "cast_required": "Cast is required",
      "phone_number_required": "Phone number is required",
      "no_client_created": "No Client has been created yet.", 
      "phone_number_invalid": "Phone number is not valid.",
      "next": "Next",
      "measurements": "Measurements",
      "enter_length": "Enter Length",
      "measurement_required": "Measurement is required",
      "enter_shoulder": "Enter Shoulder",
      "length":"Length",
      "shoulder": "Shoulder",
      "enter": "Enter",
      "arms": "Arms",
      "cuffs": "Cuffs",
      "collar": "Collar",
      "chest": "Chest",
      "fitting": "Fitting",
      "lap": "Lap",
      "pant": "Pant/Shalwat",
      "paincha": "Paincha",
      "additional_detail": "Additional Detail",
      "done": "Done",
      "skip": "Skip", 
      "enter_arms": "Enter Arms",
      "enter_cuffs": "Enter Cuffs", 
      "enter_collar": "Enter Collar",
      "enter_chest": "Enter Chest",
      "enter_fitting": "Enter Fitting", 
      "enter_lap": "Enter Lap",
      "enter_pant": "Enter Pant",
      "enter_paincha": "Enter Paincha", 
      "enter_additional_detail": "Enter Additional Detail",
      "congratulations": "Congratulations", 
      "client_info_completed": "You have completed your client information.", 
      "ok": "OK",
      "email_required": "Email is required",
      "invalid_email_format": "Invalid email format",
      "submit": "Submit", 
      "email": "Email",
      "edit_profile": "Edit Profile",
      "enter_name": "Enter a name",
      "detail": "Detail",
      "add_photos_from_device": "Add photos from device", 
      "delete_client_confirmation": "Are you sure you want to delete this client? This action cannot be undone.",
      "delete_confirmation": "Are you sure you want to delete this?",
      "cancel": "Cancel",
      "delete": "Delete",
      "save_changes": "Save changes",
      "settings": "Settings", 
      "premium": "Premium", 
      "upgrade_to_premium": "Upgrade to Premium", 
      "support": "Support", 
      "help_center": "Help center", 
      "contact_us": "Contact Us", 
      "upgrade_your_plan": "Upgrade your plan",
      "free_trial_message": "You're in your 7 days free trial",
      "switch_language": "Switch Language",
      "choose_language": "Choose Language", // en
"english": "English", // en
"urdu": "Urdu", // en
"sindhi": "Sindhi", // en
"logout": "Logout", // en


    },
    "ur": {
      "add_new_member": "نیا رکن شامل کریں",
      "watch_previous_data": "پچھلا ڈیٹا دیکھیں",
      "my_clients": "میرے کلائنٹس",
      "edit": "ترمیم کریں",
      "client_detail": "کلائنٹ کی تفصیلات",
      "full_name": "مکمل نام",
      "cast": "ذات",
      "phone_number": "فون نمبر",
      "address": "پتہ",
      "optional": "اختیاری",
      "name_required": "نام ضروری ہے۔",
      "cast_required": "ذات ضروری ہے۔",
      "phone_number_required": "فون نمبر ضروری ہے۔",
      "no_client_created": "ابھی تک کوئی کلائنٹ نہیں بنایا گیا۔",
      "phone_number_invalid": "فون نمبر درست نہیں ہے۔",
      "next": "اگلا",
      "measurements": "ماپیں", 
      "enter_length": "لمبائی درج کریں",
      "measurement_required": "ماپ ضروری ہے", 
      "length": "لمبائی",  
      "enter_shoulder": "کندھے درج کریں",
      "shoulder": "کندھا",
      "enter": "داخل کریں",  
      "arms": "بازو",  
      "cuffs": "کف",  
      "collar": "گلے",  
      "chest": "سینے",  
      "fitting": "فٹنگ",  
      "lap": "گود",  
      "pant": "پینٹ",  
      "paincha": "پینچہ",  
      "additional_detail": "اضافی تفصیل",  
      "done": "مکمل",  
      "skip": "نظر انداز کریں",
      "enter_arms": "بازو درج کریں",
      "enter_cuffs": "کف درج کریں",
      "enter_collar": "گلے درج کریں",
      "enter_chest": "سینے درج کریں", 
      "enter_fitting": "فٹنگ درج کریں",
      "enter_lap": "گود درج کریں", 
      "enter_pant": "پینٹ درج کریں", 
      "enter_additional_detail": "اضافی تفصیل درج کریں", 
      "enter_paincha": "پینچہ درج کریں",
      "congratulations": "مبارک ہو",
      "client_info_completed": "آپ نے اپنے کلائنٹ کی معلومات مکمل کر لی ہیں۔",
      "ok": "ٹھیک ہے", 
      "invalid_email_format": "ای میل کا فارمٹ غلط ہے",
      "email_required": "ای میل ضروری ہے",
      "submit": "جمع کریں",
      "email": "ای میل",
      "edit_profile": "پروفائل میں ترمیم کریں",
      "enter_name": "نام درج کریں",
      "detail": "تفصیل",
      "add_photos_from_device": "ڈیوائس سے تصاویر شامل کریں", 
      "delete": "مٹائیں", 
      "save_changes": "تبدیلیاں محفوظ کریں", 
      "delete_client_confirmation": "کیا آپ اس کلائنٹ کو حذف کرنا چاہتے ہیں؟ یہ عمل واپس نہیں کیا جا سکتا۔", 
      "delete_confirmation": "کیا آپ اس کو حذف کرنا چاہتے ہیں؟", 
      "cancel": "منسوخ کریں", 
      "settings": "سیٹنگز", 
      "premium": "پریمیم", 
      "upgrade_to_premium": "پریمیم میں اپ گریڈ کریں", 
      "support": "سپورٹ", 
      "help_center": "مدد مرکز", 
      "contact_us": "ہم سے رابطہ کریں", 
      "upgrade_your_plan": "اپنے پلان کو اپ گریڈ کریں", 
      "free_trial_message": "آپ اپنے 7 دن کے مفت ٹرائل میں ہیں",
      "switch_language": "زبان تبدیل کریں", // ur
      "choose_language": "زبان منتخب کریں", // ur
      "english": "انگریزی", // ur
      "urdu": "اردو", // ur
      "sindhi": "سندھی", // ur
      "logout": "لاگ آؤٹ", // ur
    },
    "sd": {
      "add_new_member": "نئون ميمبر شامل ڪريو",
      "watch_previous_data": "اڳيون ڊيٽا ڏسو",
      "my_clients": "منهنجا گراهڪ",
      "edit": "ترميم ڪريو",
      "client_detail": "گراهڪ جي تفصيل",
      "full_name": "مڪمل نالو",
      "cast": "ذات",
      "phone_number": "فون نمبر",
      "address": "پتو",
      "optional": "اختياري",
      "name_required": "نالو ضروري آهي.",
      "cast_required": "ذات ضروري آهي",
      "phone_number_required": "فون نمبر ضروري آهي.",
      "no_client_created": "اڃا تائين ڪو به گراهڪ نه ٺاهيو ويو آهي." ,
      "phone_number_invalid": "فون نمبر صحيح نه آهي.",
      "next": "اڳتي",
      "measurements": "ماپن", 
      "enter_length": "ڏانڌو داخل ڪريو" ,
      "measurement_required": "ماپ ضروري آهي" ,
      "length": "ڏانڌو", 
      "enter_shoulder": "کندو داخل ڪريو", 
      "shoulder": "کندو",
      "enter": "داخل ڪريو", 
      "arms": "بازو", 
      "cuffs": "کف", 
      "collar": "ڪولر", 
      "chest": "سينہ", 
      "fitting": "فٽنگ", 
      "lap": "گود", 
      "pant": "پينٽ", 
      "paincha": "پينڇو", 
      "additional_detail": "وڌيڪ تفصيل", 
      "done": "مڪمل" ,
      "skip": "گذاري ڇڏيو",
      "enter_arms": "بازو داخل ڪريو",
      "enter_cuffs": "کف داخل ڪريو",
      "enter_collar": "ڪولر داخل ڪريو",
      "enter_chest": "سينہ داخل ڪريو",
      "enter_fitting": "فٽنگ داخل ڪريو",
      "enter_lap": "گود داخل ڪريو", 
      "enter_pant": "پينٽ داخل ڪريو", 
      "enter_additional_detail": "وڌيڪ تفصيل داخل ڪريو" ,
      "enter_paincha": "پينڇو داخل ڪريو", 
      "congratulations": "مبارڪون" ,
      "client_info_completed": "توھان پنھنجي گراهڪ جون ڄاڻ مڪمل ڪيون آھن." ,
      "ok": "ٺيڪ آهي"  ,
      "invalid_email_format": "اي ميل جو فارميٽ غلط آهي" ,
      "email_required": "اي ميل ضروري آهي" ,
      "submit": "جمع ڪر",
      "edit_profile": "پروفائل ۾ تبديلي ڪريو" ,
      "enter_name": "نالو داخل ڪريو",
      "detail": "تفصيل",
      "add_photos_from_device": "ڊوائيس مان تصويرون شامل ڪريو" ,
      "delete": "مٽايو",
      "save_changes": "تبديليون محفوظ ڪريو" ,
      "delete_client_confirmation": "ڇا اوھان پڪ آھيو تھ اوھان ھن گراهڪ کي مٽائڻ چاھيو ٿا؟ ھي عمل واپس نہ ٿي سگھي ٿو." ,
      "delete_confirmation": "ڇا اوھان پڪ آھيو تھ اوھان ھن کي مٽائڻ چاھيو ٿا؟" ,
      "cancel": "منسوخ ڪريو",
      "settings": "سيٽنگون",
      "premium": "پريميئم",
      "upgrade_to_premium": "پريميئم ۾ اپ گريڊ ڪريو",
      "support": "سپورٽ",
      "help_center": "مدد مرڪز",
      "contact_us": "اسان سان رابطو ڪريو",
      "upgrade_your_plan": "پنھنجي پلان کي اپ گريڊ ڪريو" ,
      "free_trial_message": "توهان 7 ڏينهن جي مفت آزمائش ۾ آهيو",
      "switch_language": "زبان تبديل ڪريو",
"choose_language": "زبان چونڊيو",
"english": "انگريزي",
"urdu": "اردو",
"sindhi": "سنڌي",
"logout": "لاگ آئوٽ",



    }
  }
  